### ISSUE TITLE
seg for train

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#957] opened 2022-04-20 17:36 UTC
When I try to command python tools/train.py configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py --work-dir seg, it gives error:

ForkingPickler(file, protocol).dump(obj)
TypeError: can’t pickle [Environment](https://so.csdn.net/so/search?q=Environment&spm=1001.2101.3001.7020) objects.
Can you give some suggestions?

**Comment by xinke-wang** [comment] 2022-04-21 02:43
Hi, did you follow the step-by-step installation instructions to set up the MMOCR environment?

**Comment by Zhaohaojie4598** [comment] 2022-04-21 15:14
In fact ,at first , I installed pytorch1.6.0,but it doesn't work for my graphics card， so I installed pytorch 1.10.1, I don't know whether it affects?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmocr] seg for train (Issue #957)





 
Hi, did you follow the step-by-step installation instructions to set up the MMOCR environment?

**Comment by xinke-wang** [comment] 2022-04-22 03:03
Can you paste your package versions here by running `pip list`?

**Comment by Zhaohaojie4598** [comment] 2022-04-22 16:04
> Can you paste your package versions here by running `pip list`?

addict                2.4.0
albumentations        1.1.0
asynctest             0.13.0
atomicwrites          1.4.0
attrs                 21.4.0
awscli                1.22.96
botocore              1.24.41
certifi               2021.10.8
charset-normalizer    2.0.12
codecov               2.1.12
colorama              0.4.3
coverage              6.3.2
cycler                0.11.0
Cython                0.29.28
docutils              0.15.2
flake8                4.0.1
fonttools             4.32.0
future                0.18.2
idna                  3.3
imageio               2.16.2
imgaug                0.4.0
importlib-metadata    4.2.0
importlib-resources   5.6.0
iniconfig             1.1.1
isort                 5.10.1
jaraco.classes        3.2.1
jaraco.collections    3.5.1
jaraco.context        4.1.1
jaraco.functools      3.5.0
jaraco.structures     2.1.0
jaraco.text           3.7.0
jaraco.ui             2.3.0
jaraco.windows        5.7.0
jarowinkler           1.0.2
jmespath              1.0.0
joblib                1.1.0
kiwisolver            1.4.2
kwarray               0.6.0
lanms-neo             1.0.2
llvmlite              0.38.0
lmdb                  1.3.0
matplotlib            3.5.1
mccabe                0.6.1
mkl-fft               1.3.1
mkl-random            1.2.2
mkl-service           2.4.0
mmcv-full             1.4.8
mmdet                 2.23.0
mmocr                 0.5.0       d:\mmocr
more-itertools        8.12.0
networkx              2.6.3
numba                 0.55.1
numpy                 1.21.5
opencv-contrib-python 4.5.4.60
opencv-python         4.5.4.60
ordered-set           4.1.0
packaging             21.3
path                  16.4.0
Pillow                9.0.1
pip                   22.0.4
pluggy                1.0.0
py                    1.11.0
pyasn1                0.4.8
pyclipper             1.3.0.post2
pycocotools           2.0.4
pycocotools-windows   2.0.0.2
pycodestyle           2.8.0
pyflakes              2.4.0
pyparsing             3.0.8
pytest                7.1.1
pytest-cov            3.0.0
pytest-runner         6.0.0
python-dateutil       2.8.2
PyWavelets            1.3.0
PyYAML                5.4.1
qudida                0.0.4
rapidfuzz             2.0.8
regex                 2022.3.15
requests              2.27.1
rsa                   4.7.2
s3transfer            0.5.2
scikit-image          0.19.2
scikit-learn          1.0.2
scipy                 1.7.3
setuptools            62.1.0
Shapely               1.8.1.post1
six                   1.16.0
terminaltables        3.1.10
threadpoolctl         3.1.0
tifffile              2021.11.2
tomli                 2.0.1
torch                 1.10.1
torchaudio            0.10.1
torchvision           0.11.2
typing_extensions     4.1.1
ubelt                 1.0.1
urllib3               1.26.9
wheel                 0.37.1
wincertstore          0.2
xdoctest              1.0.0
yapf                  0.32.0
zipp                  3.8.0

**Comment by Zhaohaojie4598** [comment] 2022-04-23 06:49
pip list here . What should I do ?

**Comment by xinke-wang** [comment] 2022-04-23 10:51
Hi, sorry for the late reply. It seems this is a Windows-specific issue that I currently cannot reproduce on my side. My suggestion is to try to set the `workers_per_gpu=0` in the config file and see if it works.

@Mountchicken Do you have a windows device? Have you ever encountered this issue?

**Comment by Mountchicken** [comment] 2022-04-23 12:05
I can run this command successfully on my windows, here is my environment:
```bash
torch: 1.8.1+cu102
torchvision: 0.9.1+cu102
mmocr: 0.5.0
mmdet:2.21.0
mmcv-full:1.4.5
```
- @Zhaohaojie4598 Check if you have installed mmocr and pytorch correctly.

**Comment by gaotongxiao** [comment] 2022-05-09 06:51
I'm closing this issue as there have been no updates for weeks.

**Closed by gaotongxiao** 2022-05-09 06:51 UTC
