### ISSUE TITLE
lanms-proper

### ISSUE THREAD

**Issue by centurions** [open-mmlab/mmocr#230] opened 2021-05-22 20:26 UTC
Hello 
Could you please tell me what is the purpose of using lanms-proper
(very old package) that prevents mmocr from installing on windows ? :((

**Comment by innerlee** [comment] 2021-05-23 02:56
Thanks for the report! We will seek for better replacement

**Comment by innerlee** [comment] 2021-05-23 03:06
It is used in DRRG.

**Comment by centurions** [comment] 2021-05-23 20:04
Thank you

**Comment by innerlee** [comment] 2021-07-21 11:18
Hi @gaotongxiao would like to make lanms-proper as a conditional dependency? Simply wrap the related imports with try catch and move the package to requirements/optional.txt is good enough.

**Comment by gaotongxiao** [comment] 2021-07-21 11:46
OK

**Comment by ChangjieWu** [comment] 2021-07-23 16:22
The same problem occurred on mac os.

**Comment by Olli-Olli** [comment] 2021-07-28 06:27
I'd like to train the SAR model on a Windows machine for which I need to have the _lanms-proper_ package installed. Unfortunately I can't make the installation of _lansms-proper_ work.

**Comment by gaotongxiao** [comment] 2021-07-28 07:45
@Olli-Olli @ChangjieWu If you are building from source, simply remove `lanms-proper` from requirements/readthedocs.txt and requirements/readthedocs.txt should work. We are still figuring out a way to solve this issue elegantly.

**Comment by gaotongxiao** [comment] 2021-07-28 07:46
@innerlee Moving it to optional means that the package would not be installed by default even on Linux. It seems not a good idea.

**Comment by Olli-Olli** [comment] 2021-07-28 07:53
@gaotongxiao Just making the package optional indeed allows me to install mmocr. The problem is I do need that part of the code that used `lanms-proper`. Thus making it optional doesn't solve it for me.

**Comment by gaotongxiao** [comment] 2021-07-28 08:21
@Olli-Olli Unfortunately, we don't have a perfect solution for now. If you have any progress on that, please let us know :)

**Comment by gen-ko** [comment] 2021-08-21 02:25
@gaotongxiao Referred to the EAST paper implementation, I re-distributed a pip package [`lanms-neo`](https://github.com/gen-ko/lanms-neo) with sdist (so Windows as well as other platforms will be able to install via pip). The API is the same as the original one, so you should be able to just modify the `requirments.txt` and get everything work.

**Comment by gaotongxiao** [comment] 2021-08-22 03:39
@gen-ko Great! We'll apply the update asap.

**Closed** 2021-08-23 07:32 UTC
Labels: enhancement, installation, windows

**Comment by gaotongxiao** [comment] 2022-02-23 09:00
Hi @gen-ko , we recently got a feedback from an M1-chip user that `lanms-neo` requires `numpy==1.22.2` which has no available pip package for them. Would you relax the version bound for `numpy` and upgrade the package? You may share the maintainership of this package with us so that we can help you maintain it.

**Comment by gen-ko** [comment] 2022-02-23 10:37
@gaotongxiao Sure. Added you as collaborator to the repo.

**Comment by gaotongxiao** [comment] 2022-02-23 11:06
@gen-ko Thanks!
