### ISSUE TITLE
[Bug] [Bug]how to annotate multi line text for master ocr?

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmocr#1902] opened 2023-05-11 08:03 UTC
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment
[Bug]how to annotate multi line text for master ocr?

### Reproduces the problem - code sample

[Bug]how to annotate multi line text for master ocr?

### Reproduces the problem - command or script

[Bug]how to annotate multi line text for master ocr?

### Reproduces the problem - error message
[Bug]how to annotate multi line text for master ocr?

**Comment by gaotongxiao** [comment] 2023-05-11 10:51
Duplicate of #1903

**Closed by gaotongxiao** 2023-05-11 10:51 UTC
Labels: bug
