### ISSUE TITLE
 is not a checkpoint file

### ISSUE THREAD

**Issue by botastark** [open-mmlab/mmocr#326] opened 2021-06-24 15:16 UTC
OSError: panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth is not a checkpoint file
when I run with config panet/panet_r18_fpem_ffm_600e_icdar2015.py

Same with panet_r18_fpem_ffm_sbn_600e_ctw1500_20210219-3b3a9aa3.pth

**Comment by gaotongxiao** [comment] 2021-06-24 15:50
I am not able to reproduce the error. Could you provide 1) a full log of your command, 2) the results of `python mmocr/utils/collect_env.py` and 3) your GPU model?

**Comment by botastark** [comment] 2021-06-25 07:48
LOG: 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/workspace/bota/mmocr/demo/image_demo.py in <module>
     63 
     64 if __name__ == '__main__':
---> 65     main()

/workspace/bota/mmocr/demo/image_demo.py in main()
     25 
     26     # build the model from a config file and a checkpoint file
---> 27     model = init_detector(args.config, args.checkpoint, device=args.device)
     28     if model.cfg.data.test['type'] == 'ConcatDataset':
     29         model.cfg.data.test.pipeline = model.cfg.data.test['datasets'][

/usr/local/lib/python3.8/dist-packages/mmdet/apis/inference.py in init_detector(config, checkpoint, device, cfg_options)
     40     if checkpoint is not None:
     41         map_loc = 'cpu' if device == 'cpu' else None
---> 42         checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
     43         if 'CLASSES' in checkpoint.get('meta', {}):
     44             model.CLASSES = checkpoint['meta']['CLASSES']

/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py in load_checkpoint(model, filename, map_location, strict, logger, revise_keys)
    511         dict or OrderedDict: The loaded checkpoint.
    512     """
--> 513     checkpoint = _load_checkpoint(filename, map_location, logger)
    514     # OrderedDict is a subclass of dict
    515     if not isinstance(checkpoint, dict):

/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py in _load_checkpoint(filename, map_location, logger)
    449            information, which depends on the checkpoint.
    450     """
--> 451     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
    452 
    453 

/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py in load_checkpoint(cls, filename, map_location, logger)
    242         class_name = checkpoint_loader.__name__
    243         mmcv.print_log(f'Use {class_name} loader', logger)
--> 244         return checkpoint_loader(filename, map_location)
    245 
    246 

/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py in load_from_local(filename, map_location)
    258 
    259     if not osp.isfile(filename):
--> 260         raise IOError(f'{filename} is not a checkpoint file')
    261     checkpoint = torch.load(filename, map_location=map_location)
    262     return checkpoint

OSError: panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth is not a checkpoint file



ENV:
sys.platform: linux
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu102
OpenCV: 4.5.2
MMCV: 1.3.4
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMOCR: 0.2.0+bb44475


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gaotongxiao** [comment] 2021-06-25 08:47
Have you downloaded the checkpoint file to correct path? You have to download it before running script (https://mmocr.readthedocs.io/en/latest/textdet_models.html#efficient-and-accurate-arbitrary-shaped-text-detection-with-pixel-aggregation-network).

**Comment by botastark** [comment] 2021-06-25 09:40
yes! all other checkpoints except for panet are working fine.

**Comment by gaotongxiao** [comment] 2021-06-25 12:15
I have no clue about the exact reason but some comments: MMCV currently still has some compatibility issues with PyTorch 1.9.0. Also your PyTorch was compiled on cuda 10.2 while you've compiled MMCV on cuda 11.3. You may want to make the dependency of these packages consistent. 

Also, make sure your path is correct and the checkpoint file is completely downloaded. Try passing absolute path instead of the relative path may also help (https://github.com/open-mmlab/mmdetection/issues/1378)

**Comment by gaotongxiao** [comment] 2021-07-16 03:50
I'm closing this issue as there is no extra info provided.

**Closed by gaotongxiao** 2021-07-16 03:50 UTC
