### ISSUE TITLE
How can i obtain the current epoch parameters to model function

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#826] opened 2022-03-11 05:19 UTC
I find that the mmcv. runner class is called for training. However I want to pass the training current epoch parameter to model for loss function.  Not sure how I should change it in apis\train.py.

**Comment by gaotongxiao** [comment] 2022-03-11 07:18
Duplicate of https://github.com/open-mmlab/mmcv/issues/1794, we'll leave all the discussion there.

**Closed by gaotongxiao** 2022-03-11 07:18 UTC
