### ISSUE TITLE
文本检测中dbnet_r50dcnv2_fpnc_100k_iters_synthtext.py无法跑起来，请问你们是怎么配置数据集的，我按照官方文档配置根本不行，而且关于synthtext数据集如何在检测模型中使用，已经有几个人提问题了，但是没有一个具体的步骤和解决方案，希望可以给出解决的步骤，可以不？ 

### ISSUE THREAD

**Issue by manjaro-git** [open-mmlab/mmocr#1158] opened 2022-07-15 04:27 UTC
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
标题已经回答了
**Reproduction**

1. What command or script did you run?
标题已经回答了
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
没有做任何更改，而且我发现是synthtext提供的data.md根本没办法被LmdbAnnFileBackend解析,我都不明白这么明显的格式差异，为什么一直到现在都没有任何人提出，也没有解决方案。
4. What dataset did you use?
synthtext
**Environment**
我完全可以确定环境没有任何问题，完全就是官方给的data.md格式读不了的问题，而且在文档中甚至没描述data.md的格式，整个过程就寥寥几句话，太敷衍了。这种态度不仅是这里，在mmdetection中也是，单纯替换了configs中的LoadImageFromFile,但是连参数都没改，还是我手动去该参数的，虽然这个项目整体很好，但是文档的细节之类的，挺让人失望的，大部分时间都浪费在解决这种小问题上，极度让人厌恶。
1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by gaotongxiao** [comment] 2022-07-15 12:42
Our apologies for the late reply. This bug was introduced in #982. We responded to the community's request for the synthtext config via #983, but failed to realize #982, which was developed in parallel, would break this config. So, thanks for reporting this bug. My colleague has posted a hotfix in #1159. Besides, we understand our current documentation is poor and the polished documentation will be released very soon.

And here are some of my personal thoughts. This project is far from perfect and there are definitely some bugs we are not aware of, and many might be reported by our users from community. We wish this project could be cultivated and shared by everyone, so constructive suggestions/issues/comments/contributions are always welcome from any side.

However, while we try our best to respond to every issue within 24hrs, we have intensive development tasks and sometimes might not be able to give instant feedback. The bug location process is usually getting much more difficult if we do not receive a full error report in template, as we have to deduce the cause of the bug from our experience only given part of the error log. I do think current docs are poor and the code is somehow buggy, but everything would be better if we could have a healthy discussion where everyone can focus on the issue and demonstrate mutual respect. 

I'm closing this issue and we can move any further discussion about the issue back to #1156.

**Closed by gaotongxiao** 2022-07-15 12:42 UTC
