### ISSUE TITLE
How do I can transfer psenet model to tensorrt model in mmocr?

### ISSUE THREAD

**Issue by xuhui1994** [open-mmlab/mmocr#895] opened 2022-03-29 08:50 UTC
I have trained my own psenet model (train set:7000+images，test set: 1000+images，model config: /configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2017.py ) Now I want to get a psenet tensorrt model，Looking  forward your reply !

**Comment by Mountchicken** [comment] 2022-03-29 09:06
HI @xuhui1994 
Currently, MMOCR's deploy work is transferred to [MMdeploy](https://github.com/open-mmlab/mmdeploy). You can raise a claim in their [Questionnaire](https://github.com/open-mmlab/mmdeploy/issues/170). However, this may take months😫.

**Comment by gaotongxiao** [comment] 2022-03-29 09:06
A duplicate of https://github.com/open-mmlab/mmdeploy/issues/285, I'm closing it now.

**Closed by gaotongxiao** 2022-03-29 09:06 UTC

**Comment by gaotongxiao** [comment] 2022-03-29 09:10
And I'm sorry, but all the deployment questions are always handled by MMDeploy team. You can contact them for any further assistance.
