### ISSUE TITLE
Bug. The output of  ocr.readtext is not equal to the number of images but to the number of the batches. In the inference, when batch_mode =True,  

### ISSUE THREAD

**Issue by EMRAN-SALEH-CORSEARCH** [open-mmlab/mmocr#797] opened 2022-02-26 21:46 UTC
In the inference,  when we call 
results = ocr.readtext(IMAGES_FOLDER_PATH,
                                    print_result=False, 
                                    details=True,
                                    batch_mode =True,
                                   det_batch_size= 5,
                                   recog_batch_size=5)

In batch_mode. The system gives the output of one image of each batch instead of all images in each batch.
For example, if the images folder has 10 images and the batch size is= 5 so we have 2 batches. The inference output gives the results of 2 images, one image of each batch. Not the output of all images in the folder.

**Comment by gaotongxiao** [comment] 2022-02-28 02:01
Thanks for reporting! We'll look into it.

**Comment by xinke-wang** [comment] 2022-04-24 12:27
Following the descriptions, I cannot reproduce the issue.

Since everything works well on my side using the script below, I am closing this issue. If you still encounter the same issue, feel free to reopen this issue and provide more details, so we can look into where the problem is.

```python
from mmocr.utils.ocr import MMOCR

# Load models into memory
ocr = MMOCR(det='PANet_CTW', recog='SAR')

# Inference
results = ocr.readtext(
    'tests/data/toy_dataset/imgs/test/',
    output='./outputs',
    print_result=False,
    details=True,
    batch_mode=True,
    det_batch_size=5,
    recog_batch_size=5)
```

![image](https://user-images.githubusercontent.com/45810070/164976321-30727b2d-3403-4b25-b978-9cc8cbcc70af.png)

**Closed by xinke-wang** 2022-04-24 12:27 UTC
Labels: bug
